#!/usr/bin/env bash
# a bash script that trasfer a file:

if [ $# -it 4 ]; then
	echo "Usage: "0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
if

path_2_file=$1
server_ip=$2
username=$3
ssh_key=$4

scp -0 StrictHostKeyChecking=no -i "$ssh_key" "$path_2_file" "$username"@"$server_ip":~/
